### ISSUE TITLE
Revert #33 - Figure out package dependencies, and don't blindly yum update

### ISSUE THREAD

**Issue by LindsayHill** [StackStorm/bwc-installer#34]
PR #33 should be reverted.

The installation script should **not** do this sort of thing:
```sh
sudo yum -y update
```

This PR appears to stem from two issues:

1. The use of the `dcfabric-suite-installer-el7.sh` for upgrades. This is not the right path for performing upgrades. Users can & should use the script for initial installation, but upgrades should be performed using `yum` or `apt`.
2. Dependencies for the dcfabric-suite packages. It appears that the dcfabric-suite 1.2 TP package does not enforce an upgrade of `bwc-cli`, `bwc-topology` and `dcfabric-packs` packages - it looks like maybe it was only looking for `>= 1.1`, not `>=1.2`?

**Comment by rmadapur** [comment]
[vagrant@win7test ~]$ yum deplist dcfabric-suite-1.2-3.x86_64
Loaded plugins: fastestmirror, security
Finding dependencies:
Loading mirror speeds from cached hostfile
 * base: ftp.linux.ncsu.edu
 * epel: mirror.umd.edu
 * extras: mirror.team-cymru.org
 * updates: mirror.umd.edu
package: dcfabric-suite.x86_64 1.2-3
  dependency: bwc-cli >= 1.2
   provider: bwc-cli.x86_64 1.0.0-1
   provider: bwc-cli.x86_64 1.2-1
   provider: bwc-cli.x86_64 1.0.0-1
   provider: bwc-cli.x86_64 1.1-1
  dependency: /bin/sh
   provider: bash.x86_64 4.1.2-48.el6
  dependency: dcfabric-packs >= 1.2
   provider: dcfabric-packs.x86_64 1.2-1
  dependency: bwc-topology >= 1.2
   provider: bwc-topology.x86_64 1.0.0-10
   provider: bwc-topology.x86_64 1.0.0-7
   provider: bwc-topology.x86_64 1.0.0-8
   provider: bwc-topology.x86_64 1.0.0-9
   provider: bwc-topology.x86_64 1.1-1
   provider: bwc-topology.x86_64 1.1-2
   provider: bwc-topology.x86_64 1.2-1
   provider: bwc-topology.x86_64 1.0.0-10
   provider: bwc-topology.x86_64 1.0.0-11
   provider: bwc-topology.x86_64 1.0.0-2
   provider: bwc-topology.x86_64 1.0.0-9
   provider: bwc-topology.x86_64 1.1-2

The depedency for bwc-topology and bwc-cli are both greater than 1.2. However there are multiple providers

**Comment by LindsayHill** [comment]
OK, I have found the problem. It is in the packaging of bwc-cli and bwc-topology, specifically the `Provides` line.
[bwc-cli](https://github.com/StackStorm/bwc-cli/blob/master/packages/rpm/bwc-cli.spec#L19)
```ruby
Source0: .
Provides: bwc-cli
Summary: CLI for Brocade Workflow Composer
```
[bwc-topology](https://github.com/StackStorm/bwc-topology/blob/master/rpm/bwc-topology.spec#L34)
```ruby
%define package bwc-topology
...
Source0: bwc-topology
Provides: %{package}
```

This is wrong. These packages should not explicitly set a 'Provides' line, unless it is for a virtual package name.

The result of having that line is this:
```sh
[vagrant@bwcvagrant ~]$ rpm -q --provides bwc-cli
bwc-cli
bwc-cli = 1.1-1
bwc-cli(x86-64) = 1.1-1
[vagrant@bwcvagrant ~]$ rpm -q --provides bwc-topology
bwc-topology
bwc-topology = 1.1-1
bwc-topology(x86-64) = 1.1-1
[vagrant@bwcvagrant ~]$ rpm -q --provides dcfabric-packs
dcfabric-packs = 1.1-1
dcfabric-packs(x86-64) = 1.1-1
[vagrant@bwcvagrant ~]$
```
Note how `dcfabric-packs` **only** has lines with specific versions. This is because it does **not** have a `Provides: dcfabric-packs` line in its spec file.

The problem is that the `dcfabric-suites` package says that it requires `bwc-topology >= 1.2` and `bwc-cli >= 1.2`. But because those already installed packages say they provide `bwc-cli` and `bwc-topology`, yum decides that it is sufficient, and so it does not need to upgrade those packages. 

The fix here is to remove the `Provides` line from those spec files & rebuild the packages. This will not fix the problem for existing customers, at least not until they perform an upgrade.

Their upgrade procedure should be to run `sudo yum -y update dcfabric-suite dcfabric-packs bwc-cli bwc-topology`.

It should **not** be to do a blind `sudo yum -y update` - that command effectively updated those packs too, but it was a big hammer, making far more changes than necessary.
